services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: web
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEMO_MODE=${DEMO_MODE:-false}
    volumes:
      - ./outputs:/app/outputs
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: api
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEMO_MODE=${DEMO_MODE:-false}
    volumes:
      - ./outputs:/app/outputs
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
